/items/{user_id}のハンドラを追加しました
nunupy345345/Dots_to_code2024_back pull request #12
Opened 2024-03-20 09:47 UTC by nunupy345345

/items/{user_id}のハンドラを追加しました。
確認お願いします！ @nac-39

2024-03-20 14:25 UTC, nac-39 requested changes
諸々の細かい修正を入れました…！ちょっと多いと思うんだけど、修正してもらえると嬉しいです！
あと、動作確認がまだ完了していないので、動作確認ができたらそのスクショとかcurlのコマンドとかでもいいんだけど送ってほしいです！

2024-03-20 14:25 UTC, nac-39 commented on app/handler/item.py
> +        selected_items = random.sample(items, 6)
itemsが6個以下のときにエラーになってしまうので、それに対応してほしいです！

↓エラー文
```
Sample larger than population or is negative
```

2024-03-20 14:25 UTC, nac-39 commented on app/handler/item.py
> +        response = items
多分、`response = selected_items`だと思うのですが、それでも`selected_items`がpydanticの形じゃないのでエラーになります。
`selected_items`をレスポンスの型に変換する部分を書いてほしいです！

2024-03-20 14:25 UTC, nac-39 commented on app/handler/item.py
> +        response = items
(レスポンスが`response.model_dump_json()`になっているのですが、`model_dump_json()`が使えるのはpydanticの`BaseModel`とかを継承した型（クラス）だけだと思います。)

2024-03-20 14:34 UTC, nac-39 commented
# ごめん！！！
/items/{{user_id}}のほうの変更と勘違いしていて、こっちに必要ないレビューまで書いちゃってました！！！！
適当に無視してもらえるとありがたいです！！

2024-03-21 00:19 UTC, nunupy345345 commented
タイトルを付け替えるのを忘れました！！本当にすみません！！

2024-03-21 00:50 UTC, nunupy345345 commented
reviewありがとうございます！反映しました(errorメッセージは別のPRで修正しました)！
![image](https://github.com/nunupy345345/Dots_to_code2024_back/assets/131859242/b7df92f7-4506-480c-a8ab-4cafc6451199)

2024-03-21 02:57 UTC, nac-39 approved these changes
修正ありがとう〜！！！テストもうまく行っているようだしマージします！

2024-03-21 02:58 UTC, merged